rapidsai/cugraph-gnn

ci/check_style.sh, ci/test_cpp.sh, ci/test_notebooks.sh, ci/test_python.sh
Contributes to https://github.com/rapidsai/dependency-file-generator/issues/89
Uses `--file-key` instead of `--file_key` in `rapids-dependency-file-generator` calls in CI scripts, as `file_key` is deprecated and set to be removed.
=> resolve dependency-file-generator warning

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-121_arch-x86_64.yaml, dependencies.yaml, python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-118.yaml, python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-118.yaml
Fixes issues with DGL dependencies.  The environment files should be usable now.
=> Fix Issues with DGL Dependencies

python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_mnmg.py
Applies rapidsai/cugraph#4532 to this repository.
=> [IMP] Set the Default WG Memory Type to 'distributed' for the MNMG PyG Example (rapidsai/cugraph#4532)

dependencies.yaml
Contributes to https://github.com/rapidsai/build-planning/issues/31
`cugraph-gnn` does not currently used `rapids-build-backend`, but this will help once it does. I wrote that up here: https://github.com/rapidsai/cugraph-gnn/issues/15
In short, RAPIDS DLFW builds want to produce wheels with unsuffixed dependencies, e.g. `cudf` depending on `rmm`, not `rmm-cu12`.
This PR is part of a series across all of RAPIDS to try to support that type of build by setting up CUDA-suffixed and CUDA-unsuffixed dependency lists in `dependencies.yaml`.
For more details, see:
* https://github.com/rapidsai/build-planning/issues/31#issuecomment-2245815818
* https://github.com/rapidsai/cudf/pull/16183
This is targeting 24.08 because:
1. it should be very low-risk
2. getting these changes into 24.08 prevents the …
=> split up CUDA-suffixed dependencies in dependencies.yaml

.pre-commit-config.yaml
Contributes to https://github.com/rapidsai/build-planning/issues/88.
Fixes one Python 3.9 to 3.10 upgrade that was missed in #32.
=> upgrade target Python version for black to 3.10

python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_mnmg.py, python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_snmg.py, python/cugraph-pyg/cugraph_pyg/examples/rgcn_link_class_mnmg.py, python/cugraph-pyg/cugraph_pyg/examples/rgcn_link_class_snmg.py
For the multi-GPU examples, we set `RAPIDS_NO_INITIALIZE` to prevent RAPIDS from creating a CUDA context.  However, this had no effect because there were some RAPIDS imports before that.  This PR resolves that problem by moving those imports elsewhere.
=> [BUG] Fix Import Order

.github/workflows/pr.yaml, .github/workflows/test.yaml, .gitignore, build.sh, ci/build_cpp.sh, ci/build_python.sh, ci/test_notebooks.sh, ci/test_python.sh, ci/utils/nbtest.sh, conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-121_arch-x86_64.yaml, conda/environments/all_cuda-124_arch-x86_64.yaml, conda/recipes/cugraph-dgl/meta.yaml, conda/recipes/cugraph-pyg/meta.yaml, datasets/get_test_data.sh, dependencies.yaml, python/cugraph-dgl/examples/dataset_from_disk_cudf.ipynb
Closes #53
This pulls over the remaining changes from that PR... thought that was easier than fixing the merge conflicts between that and recent PRs.
* adds notebook testing
* adds all the remaining `build.sh` changes from #53 (mostly for interactive development)
* adds `cugraph-pyg` and `cugraph-dgl` tests in `conda-python-tests` (missed in #59)
I left other comments explaining these changes inline.
=> add notebook tests, build.sh args

.github/workflows/build.yaml
Adds package-publishing workflows.
This should not be merged until the following are done:
=> start publishing packages

ci/build_wheel_cugraph-dgl.sh, ci/build_wheel_cugraph-pyg.sh, ci/build_wheel_pylibwholegraph.sh, ci/validate_wheel.sh, python/cugraph-dgl/pyproject.toml, python/cugraph-pyg/README.md, python/cugraph-pyg/pyproject.toml, python/pylibwholegraph/README.md, python/pylibwholegraph/pyproject.toml
Contributes to https://github.com/rapidsai/build-planning/issues/110
Proposes adding 2 types of validation on wheels in CI, to ensure we continue to produce wheels that are suitable for PyPI.
* checks on wheel size (compressed),
- *to be sure they're under PyPI limits*
- *and to prompt discussion on PRs that significantly increase wheel sizes*
* checks on README formatting
- *to ensure they'll render properly as the PyPI project homepages*
- *e.g. like how https://github.com/scikit-learn/scikit-learn/blob/main/README.rst becomes https://pypi.org/project/scikit-learn/*
=> enforce wheel size limits, README formatting in CI

ci/build_cpp.sh, ci/build_python.sh, ci/release/update-version.sh, ci/test_notebooks.sh, ci/test_python.sh
Within this release, packages here moved from https://github.com/rapidsai/cugraph and https://github.com/rapidsai/wholegraph to this repo.
To avoid conflicts between nightlies produced from the different sources, CI scripts here were hard-coding the version for CI artifacts to `24.12.00a1000`. That should be removed now that this is the only repo packages are being published from (should have been removed in #66 , sorry for missing it).
=> remove versioning workaround for nightlies

conda/environments/all_cuda-121_arch-x86_64.yaml, conda/environments/all_cuda-124_arch-x86_64.yaml, dependencies.yaml
Fixes some small `dependencies.yaml` issues to get devcontainers builds of these libraries working.
Namely:
* wholegraph needs NVML in its build environment
* `pytorch-cuda` should be omitted when building on a CUDA minor version that it doesn't explicitly provide packages for
Pointed https://github.com/rapidsai/devcontainers/pull/417 at this branch and saw it pass.
=> fix devcontainer builds

python/pylibwholegraph/pylibwholegraph/tests/wholegraph_torch/ops/test_wholegraph_gather_scatter.py, python/pylibwholegraph/pylibwholegraph/torch/tensor.py, python/pylibwholegraph/pylibwholegraph/torch/wholememory_ops.py
Migrated from:  https://github.com/rapidsai/wholegraph/pull/229 
This PR is to add gather/scatter support 1D tensor on python level, as WholeGraph should support basic indexing operations for both 1D (array) and 2D (matrix) wholememory tensors.   Without this PR, if with 1D wholememory tensor, gather/scatter op does not work, e.g., https://github.com/rapidsai/wholegraph/blob/0efba33835d6e4e104b5d7101a91e0ea55a6ca53/python/pylibwholegraph/pylibwholegraph/torch/tensor.py#L89
To test, run 
```
pytest --cache-clear  --import-mode=append  tests/wholegraph_torch/ops/test_wholegraph_gather_scatter.py -s
```
**Remaining issue:**
On my local test with single GPU, the test can pass.   
For multiGPU setup, gather op works fine, but 1D scatter seems not working as it would crash at: …
=> [Feature] Add gather/scatter support 1D tensor

cpp/src/nvml_wrap.cpp, cpp/src/nvml_wrap.h, cpp/src/wholememory/communicator.cpp, cpp/src/wholememory/system_info.cpp, cpp/src/wholememory/system_info.hpp
[File PR here for the record]
Dynamically load NVML symbols for querying GPU fabric info to address incompatibility issues with outdated display drivers.
=> [Bugfix] Dynamic load NVML symbols for better compatibility

.github/workflows/pr.yaml, .github/workflows/test.yaml
All of this repo's `conda-python-tests` jobs have conditions in them like "skip on ARM":
https://github.com/rapidsai/cugraph-gnn/blob/2dd300122dfd6fdea70c9d20c276a3c5946b7613/ci/test_python.sh#L100
https://github.com/rapidsai/cugraph-gnn/blob/2dd300122dfd6fdea70c9d20c276a3c5946b7613/ci/test_python.sh#L141
https://github.com/rapidsai/cugraph-gnn/blob/2dd300122dfd6fdea70c9d20c276a3c5946b7613/ci/test_python.sh#L183
As a result, right now the arm64 `conda-python-tests` jobs are just wasting CI resources... they're spending ~40+~ 5-10 minutes occupying a GPU runner just to download some datasets and then exit ([example build link](https://github.com/rapidsai/cugraph-gnn/actions/runs/11858773988/job/33056063652?pr=69)).
This proposes never even starting those jobs, to make CI here less …
=> skip conda-python-tests on arm64

.github/workflows/test.yaml
Disables RockyLinux tests for DGL due to GLIBCXX version issues.  Disables 11.4 tests since they are incompatible with PyTorch.
=> Disable RockyLinux Tests for DGL, Disable CUDA All 11.4 Tests

.github/workflows/build.yaml
The branch build triggered by merging #96 failed immediately.
> The workflow is not valid. .github/workflows/build.yaml (Line: 47, Col: 12): Job 'docs-build' depends on unknown job 'conda-cpp-build'.
([build link](https://github.com/rapidsai/cugraph-gnn/actions/runs/12379736454))
This fixes that.
=> fix nightly docs workflow dependencies

.pre-commit-config.yaml, ci/build_cpp.sh, ci/build_docs.sh, ci/release/update-version.sh, conda/recipes/pylibwholegraph/meta.yaml, cpp/CMakeLists.txt, cpp/Doxyfile, python/pylibwholegraph/CMakeLists.txt
Proposes some miscellaneous packaging cleanup:
* sets minimum CMake version to 3.26.4 everywhere, to match the rest of RAPIDS
* removes commented-out CMake code
* removes unnecessary variables throughout CMake code
- *including consolidating version references to use `RAPIDS_VERSION` from https://github.com/rapidsai/cugraph-gnn/blob/af22a1271251dc6b02d91cd593ac32b504356b8d/rapids_config.cmake#L20*
* updates some `pre-commit` hooks to their latest versions
=> simplify wholegraph CMake, other small building and testing changes

.github/workflows/test.yaml
The nightly tests have been failing despite all runs succeeding because the workflow's logic for filtering out notebook runs is invalid. Examples: https://github.com/rapidsai/cugraph-gnn/actions/runs/12649473784, https://github.com/rapidsai/cugraph-gnn/actions/runs/12609514484. Hopefully this change is sufficient to get the nightly suite passing.
=> Remove invalid conditional

.github/workflows/test.yaml
The pull-request input is simply wrong, while the other inputs are necessary to pull the correct artifacts.
=> Fix inputs for the workflow

conda/environments/all_cuda-121_arch-x86_64.yaml, conda/environments/all_cuda-124_arch-x86_64.yaml, conda/recipes/cugraph-pyg/conda_build_config.yaml, conda/recipes/libwholegraph/conda_build_config.yaml, conda/recipes/libwholegraph/meta.yaml, conda/recipes/pylibwholegraph/conda_build_config.yaml, conda/recipes/pylibwholegraph/meta.yaml, dependencies.yaml
conda-forge is using GCC 13 for CUDA 12 builds. This PR updates CUDA 12 conda builds to use GCC 13, for alignment.
These PRs should be merged in a specific order, see https://github.com/rapidsai/build-planning/issues/129 for details.
=> Use GCC 13 in CUDA 12 conda builds.

.github/workflows/build.yaml, .pre-commit-config.yaml, ci/build_wheel.sh, ci/build_wheel_pylibwholegraph.sh, ci/check_style.sh, ci/test_wheel_cugraph-dgl.sh, ci/test_wheel_cugraph-pyg.sh, ci/test_wheel_pylibwholegraph.sh, cpp/CMakeLists.txt, cpp/bench/CMakeLists.txt, cpp/cmake/config.json, cpp/cmake/thirdparty/get_nccl.cmake, cpp/cmake/thirdparty/get_nvshmem.cmake, cpp/cmake/thirdparty/get_raft.cmake, cpp/scripts/run-cmake-format.sh, cpp/tests/CMakeLists.txt, python/pylibwholegraph/CMakeLists.txt, python/pylibwholegraph/pylibwholegraph/binding/CMakeLists.txt, rapids_config.cmake
Part of https://github.com/rapidsai/build-planning/issues/136, which tracks some building/packaging simplifications and conventions we'd like to standardize across RAPIDS.
This proposes the following:
* using `cmake-format` to autoformat CMake code
* using `cmake-lint` to enforce style preferences for CMake code
* removing unnecessary use of `-DDETECT_CONDA_ENV` for wheel builds
* explicitly passing package type to GitHub Actions / `gha-tools` things handling wheels
The `cmake-format` / `cmake-lint` approach was copied directly from RAFT:
* https://github.com/rapidsai/raft/blob/596d4b7338e62a92652503cd76feaeaa187ad740/.pre-commit-config.yaml#L52
* https://github.com/rapidsai/raft/blob/596d4b7338e62a92652503cd76feaeaa187ad740/cpp/cmake/config.json
* …
=> enforce `cmake-format` and `cmake-lint`, other small packaging changes

python/pylibwholegraph/examples/node_classfication.py, python/pylibwholegraph/pylibwholegraph/torch/__init__.py, python/pylibwholegraph/pylibwholegraph/torch/data_loader.py
quick fix to create_node_classification function: use data_and_label dict as the parameter instead of pickle_data_path
=> Fix of create_node_classification_datasets

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-121_arch-x86_64.yaml, conda/environments/all_cuda-124_arch-x86_64.yaml, conda/recipes/cugraph-dgl/meta.yaml, conda/recipes/cugraph-pyg/meta.yaml, dependencies.yaml
CuPy 13.2 released a major fix that resolved an ongoing issue with NCCL (https://github.com/rapidsai/cugraph/issues/4465).  At this point, we are relying on other constraints to enforce the CuPy version, but to be safe, we should explicitly upgrade it.
Closes #22
=> Update CuPy Version to 13.2

ci/build_wheel.sh, ci/test_wheel_cugraph-dgl.sh, ci/test_wheel_cugraph-pyg.sh, ci/test_wheel_pylibwholegraph.sh
Uses a retry wrapper for `pip` commands to try to alleviate CI failures due to hash mismatches that result from network hiccups
xref rapidsai/build-planning#148
This will retry failures that show up in CI like:
```
Collecting nvidia-cublas-cu12 (from libraft-cu12==25.2.*,>=0.0.0a0)
Downloading https://pypi.nvidia.com/nvidia-cublas-cu12/nvidia_cublas_cu12-12.8.3.14-py3-none-manylinux_2_27_aarch64.whl (604.9 MB)
━━━━━━━━━━━━━━━━━━━━━                 350.2/604.9 MB 229.2 MB/s eta 0:00:02
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
nvidia-cublas-cu12 from …
```
=> Use `rapids-pip-retry` in CI jobs that might need retries

python/cugraph-pyg/cugraph_pyg/loader/link_loader.py, python/cugraph-pyg/cugraph_pyg/loader/node_loader.py
Closes #130 .  Will be accompanied by a PR to `cugraph` that shows how many batches reached each worker, so it is obvious when there are more GPUs than batches.
Resolves a bug where `drop_last` deleted all input if the length of the input modulo batch size was 0.
=> [BUG] Fix bug with drop_last when mod is 0

conda/environments/all_cuda-118_arch-x86_64.yaml, conda/environments/all_cuda-121_arch-x86_64.yaml, conda/environments/all_cuda-124_arch-x86_64.yaml, conda/recipes/cugraph-dgl/meta.yaml, dependencies.yaml, python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-118.yaml
Update the DGL packages to those using PyTorch 2.4, since the DGL 2.4 packages for PyTorch 2.3 are no longer available.  Should unblock CI.
=> Update DGL Packages to PyTorch 2.4

ci/build_docs.sh, ci/release/update-version.sh, ci/test_cpp.sh, ci/test_python.sh, dependencies.yaml
Issue: https://github.com/rapidsai/build-planning/issues/22
=> Create Conda CI test env in one step

ci/build_cpp.sh, ci/build_python.sh, ci/test_notebooks.sh, ci/test_python.sh, python/cugraph-dgl/README.md
This changes from `conda mambabuild` to `conda build`. Conda now uses the mamba solver so no performance regressions are expected.
This is a temporary change as we plan to migrate to `rattler-build` in the near future. However, this is needed sooner to drop `boa` and unblock Python 3.13 migrations.
xref: https://github.com/rapidsai/build-planning/issues/149
=> Use conda-build instead of conda-mambabuild

ci/release/update-version.sh
Add a new dependency to `update-version.sh`. Also ensure the alpha-specs are preserved.
Skips CI since this script is not tested in CI
=> Fix update version

ci/test_wheel_cugraph-pyg.sh, conda/environments/all_cuda-126_arch-x86_64.yaml, dependencies.yaml
Updates the PyTorch test dependency to install the version for CUDA 12.6.  This is the latest CUDA version supported by PyTorch.  CUDA 12.1 support is being dropped.
Closes #154
=> Update PyTorch to use CUDA 12.6

python/cugraph-pyg/cugraph_pyg/data/__init__.py
First step in handling #159 .  The unified API will store all data in WholeGraph, which has superior performance and lower memory usage.  `TensorDictFeatureStore` is no longer a useful alternative.
=> Deprecate TensorDictFeatureStore in cuGraph-PyG

cmake/RAPIDS.cmake, cmake/rapids_config.cmake, cpp/CMakeLists.txt, python/pylibwholegraph/CMakeLists.txt
This works around a problem where GitHub is rejecting requests to the `githubusercontent.com` CDN. We vendor the contents of `RAPIDS.cmake` from `rapidsai/rapids-cmake` to avoid a network call.
xref: https://github.com/rapidsai/rapids-cmake/pull/809
xref: https://github.com/rapidsai/build-infra/issues/206
=> Vendor RAPIDS.cmake

.github/workflows/pr.yaml, python/cugraph-dgl/cugraph_dgl/__init__.py, python/cugraph-dgl/cugraph_dgl/convert.py, python/cugraph-dgl/cugraph_dgl/dataloading/__init__.py, python/cugraph-dgl/cugraph_dgl/tests/dataloading/test_dask_dataloader.py, python/cugraph-dgl/cugraph_dgl/tests/dataloading/test_dask_dataloader_mg.py
Hotfix to release 25.04 that adds deprecation warnings for the dask API in cuGraph-DGL, which is no longer maintainable and needs to be removed by release 25.08.  Also adds a warning on import informing users that the cuGraph-DGL is no longer under active development and that we recommend users migrate to cuGraph-PyG.
=> [HOTFIX] Add deprecation warnings for DGL classes

.github/workflows/build.yaml
Followup and fixes for #182
I forget to update "build-type" when copying over the new job from `py.yaml` to
`build.yaml` so nightly jobs were looking for an artifact in the nightly bucket
path, but the artifacts were uploaded to the pr path.
Also added a wheel publish step which I missed in the first PR.
=> fix(libwholegraph): set build_type to "nightly" and also publish wheel

.github/workflows/build.yaml, .github/workflows/pr.yaml, .github/workflows/test.yaml, .github/workflows/trigger-breaking-change-alert.yaml, dependencies.yaml, python/cugraph-pyg/pyproject.toml, python/pylibwholegraph/pyproject.toml
Contributes to https://github.com/rapidsai/build-planning/issues/120
This PR adds support for Python 3.13.
This is part of ongoing work to add Python 3.13 support across RAPIDS.
It temporarily introduces a build/test matrix including Python 3.13, from https://github.com/rapidsai/shared-workflows/pull/268.
A follow-up PR will revert back to pointing at the `branch-25.06` branch of `shared-workflows` once all
RAPIDS repos have added Python 3.13 support.
CI here is expected to fail until all of this project's upstream dependencies support Python 3.13.
This can be merged whenever all CI jobs are passing.
=> Add support for Python 3.13

conda/recipes/cugraph-dgl/recipe.yaml, conda/recipes/cugraph-pyg/recipe.yaml, conda/recipes/libwholegraph/recipe.yaml, conda/recipes/pylibwholegraph/recipe.yaml
This quotes `head_rev` to ensure that commits with leading zeros in the git SHA include those zeros in the output package name.
xref: https://github.com/rapidsai/build-planning/issues/176
=> Quote head_rev in conda recipes

ci/build_wheel_pylibwholegraph.sh
Follow-up to #189
Replaces one more use of `rapids-download-wheels-from-s3` with `rapids-download-wheels-from-github`.
Gets this project one step closer to not relying on `downloads.rapids.ai` for passing around conda packages and wheels.
Searched for stranded references like this:
```shell
git grep -E '\-s3'
```
=> use GitHub Actions artifacts

.pre-commit-config.yaml, cpp/src/wholememory/communicator.cpp, cpp/src/wholememory/file_io.cpp, cpp/src/wholememory/memory_handle.cpp
Contributes to https://github.com/rapidsai/build-planning/issues/177
This PR updates the clang version to 20.
=> Update to clang 20

ci/test_notebooks.sh, dependencies.yaml, python/cugraph-dgl/cugraph_dgl/tests/test_graph_mg.py
Fixes a cuGraph-DGL test that crashes/hangs with 3+ GPUs.  Should resolve the issues seen by the container team.  Drops the requirement for `DGL` from notebook tests to unblock CI.
=> [BUG] Fix DGL Test

.github/workflows/build.yaml, .github/workflows/pr.yaml, .github/workflows/test.yaml, ci/build_wheel_cugraph-dgl.sh, ci/build_wheel_cugraph-pyg.sh, ci/build_wheel_libwholegraph.sh, ci/build_wheel_pylibwholegraph.sh, ci/test_wheel_cugraph-dgl.sh, ci/test_wheel_cugraph-pyg.sh, ci/test_wheel_pylibwholegraph.sh
Proposes a batch of small, mostly-unrelated changes to building and packaging.
These are all part of RAPIDS-wide efforts to make it easier to reproduce CI locally and to use artifacts from one project's CI in another project's CI.
Contributes to https://github.com/rapidsai/build-planning/issues/178
* prevents triggering expensive CI jobs based on PRs modifying `ci/release/update-version.sh`
Contributes to https://github.com/rapidsai/shared-workflows/issues/356
* explicitly provides an input for `script` to workflows using it, instead of relying on a default value coming from the workflow file
Contributes to https://github.com/rapidsai/shared-workflows/issues/337
* switches from input `run_script` to `script` in uses of the `custom-job` workflow
Contributes to …
=> use 'rapids-init-pip' in wheel CI, other CI changes

.github/workflows/build.yaml
Contributes to https://github.com/rapidsai/build-planning/issues/181
Follow-up to #215 
Now that https://github.com/rapidsai/shared-workflows/pull/364 has been merged to `branch-25.08`, this project's CI configurations should stop pointing at the branch from that PR.
=> use branch-25.08 of shared-workflows

.pre-commit-config.yaml, conda/environments/all_cuda-128_arch-aarch64.yaml, conda/environments/all_cuda-128_arch-x86_64.yaml, dependencies.yaml, python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-128_arch-aarch64.yaml, python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-128_arch-x86_64.yaml
Now that we have dropped support for CUDA 11 we no longer require the nvidia channel.
With the changes in https://github.com/rapidsai/rapids-dask-dependency/pull/85, RAPIDS now only uses released versions of dask, so we no longer need the dask channel either.
Contributes to https://github.com/rapidsai/build-planning/issues/184
=> Remove nvidia and dask channels

python/cugraph-pyg/cugraph_pyg/tensor/dist_tensor.py
Pin CPU memory when loading to WholeGraph to avoid copying more data than the GPU can hold.  This was always the intended behavior of WholeGraph tensors - this PR fixes that and resolves this critical bug blocking GraphRAG workflows.
=> [BUG] Pin CPU Memory Instead of Copying to Device

.github/CODEOWNERS, .github/workflows/pr.yaml
Contributes to https://github.com/rapidsai/build-planning/issues/203
Follow-up to #210 
* removes a `CODEOWNERS` rule referencing `cugraph-dgl/`
* updates `changed-files` so that future PRs only modifying `CODEOWNERS` won't trigger a full CI run
Found these like this:
```shell
git grep -i dgl
```
=> remove cugraph-dgl CODEOWNERS rule, skip most CI on CODEOWNERS-only PRs

ci/run_cugraph_pyg_pytests.sh, ci/test_wheel_cugraph-pyg.sh
The cuGraph-PyG examples cannot be reliably tested in CI due to memory constraints.  We will need to come up with a new strategy for testing/verifying these examples going forward.
=> [CI] Disable Example Tests

ci/build_wheel.sh, ci/build_wheel_pylibwholegraph.sh, ci/test_wheel_pylibwholegraph.sh, cpp/CMakeLists.txt, dependencies.yaml, python/cugraph-pyg/pyproject.toml, python/libwholegraph/CMakeLists.txt, python/libwholegraph/pyproject.toml, python/pylibwholegraph/pyproject.toml
Fixes #281
Similar to https://github.com/rapidsai/cuvs/pull/827, proposes that wheels get their copy of `libnccl.so` at runtime from `nvidia-nccl-cu{12,13}` wheels, instead of vendoring a copying inside `libwholegraph`.
* **I think this fill fix the nightly tests**
- _@alexbarghi-nv investigated offline and together with some other people found that "competing `libnccl` between this project and `pytorch`" may be to blame for the failing nightly tests_
* smaller `libwholegraph` wheels
- _120 MiB smaller!_
- _now they can go on `pypi.org` without needing an exception_ 🎉 🎉 🎉 
* smaller disk footprint for environments
- *via avoiding multiple copies of `libnccl.so`*
* reduced risks of runtime bugs caused by multiple competing `libnccl.so` being loaded
=> libwholegraph wheels: use nvidia-nccl wheels instead of vendoring libnccl.so

.pre-commit-config.yaml, build.sh
While trying to add CUDA 13 builds here, I discovered that this project's `build.sh` script has a hard-coded list of CUDA architectures:
https://github.com/rapidsai/cugraph-gnn/blob/c50d56d0d4987c587e6f377dd4eb9537f3d0440b/build.sh#L212
As described in https://github.com/rapidsai/cugraph-gnn/pull/286#discussion_r2319479909, this proposes removing that hard-coded list in favor of using the `"RAPIDS"` set of architectures from `rapids-cmake`.
This also updates some `pre-commit` hooks versions (unrelated, but low-risk and wanted to take advantage of the CI runs).
* keeps this project aligned with the rest of RAPIDS on CUDA architectures
- reduces the manual effort required to support new CUDA versions
- avoids the build time and binary size from building for older architectures that RAPIDS …
=> build with RAPIDS CUDA architectures

python/cugraph-pyg/cugraph_pyg/examples/taobao_mnmg.py
The Taobao example does not specify the input type of the edges when creating a `LinkNeighborLoader`, which is invalid since this is a heterogeneous graph.  This PR fixes this by specifying the correct input type, `('user', 'to', 'item')`.
=> [BUG] Fix input type in Taobao example

.github/workflows/pr.yaml, .github/workflows/test.yaml
RAPIDS recently started building and testing against CUDA 13.0.1:
* https://github.com/rapidsai/ci-imgs/pull/304
* https://github.com/rapidsai/shared-workflows/pull/423
This makes the "skip `conda-python-tests` jobs on CUDA 13" condition in CI configs a bit more generic, so we won't start picking up CUDA 13.0.1 jobs when this project isn't yet ready for them (#296).
=> fix condition to skip CUDA 13 conda-python-tests jobs

python/cugraph-pyg/cugraph_pyg/data/graph_store.py, python/cugraph-pyg/cugraph_pyg/loader/link_loader.py, python/cugraph-pyg/cugraph_pyg/loader/link_neighbor_loader.py, python/cugraph-pyg/cugraph_pyg/loader/neighbor_loader.py, python/cugraph-pyg/cugraph_pyg/loader/node_loader.py, python/cugraph-pyg/cugraph_pyg/sampler/distributed_sampler.py, python/cugraph-pyg/cugraph_pyg/sampler/sampler.py, python/cugraph-pyg/cugraph_pyg/tests/loader/test_neighbor_loader.py
Enables temporal sampling in cuGraph-PyG with some constraints:
1. Only supports sampling forward in time (probably an API violation)
2. Does not support time overrides (definitely an API violation)
Closes #116
=> [FEA] Enable Temporal Sampling in cuGraph-PyG

dependencies.yaml
Some of the dependencies listed in `dependencies.yaml` (specifically for `pylibcugraph`) in release 25.10 mistakenly reference 25.08 versions.  This PR corrects this issue.
=> [BUG] Update 25.08 Dependencies to 25.10
